name: morsecode
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  flutter_bloc: ^6.0.6
  font_awesome_flutter: ^8.10.0
  get_it: ^5.0.1
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
